---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-config-pvc
  namespace: codeserver
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-customized
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deployment
  namespace: codeserver
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
        - name: codeserver
          image: lscr.io/linuxserver/code-server:4.98.2
          ports:
            - containerPort: 8443
          env:
            - name: DOCKER_MODS
              value: "linuxserver/mods:code-server-docker|linuxserver/mods:code-server-extension-arguments"
            - name: VSCODE_EXTENSION_IDS
              value: "arcticicestudio.nord-visual-studio-code|dracula-theme.theme-dracula|eamodio.gitlens|golang.go|HashiCorp.HCL|HashiCorp.terraform|ms-azuretools.vscode-docker|ms-python.python|redhat.ansible|redhat.vscode-xml|redhat.vscode-yaml|streetsidesoftware.code-spell-checker|vscode-icons-team.vscode-icons"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: codeserver-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-service
  namespace: codeserver
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8443
      port: 8443
      protocol: TCP
  selector:
    app: codeserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ingress
  namespace: codeserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: 4096
    cert-manager.io/private-key-rotation-policy: Always
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: codeserver.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeserver-service
                port:
                  number: 8443
  tls:
    - hosts:
        - codeserver.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: codeserver-tls
